package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command


import (
  "io"
  "net/http"

  "github.com/go-openapi/runtime"
  "github.com/go-openapi/swag"
  "github.com/go-openapi/errors"
  "github.com/go-openapi/validate"
  "github.com/go-openapi/runtime"

  strfmt "github.com/go-openapi/strfmt"

  "github.com/abourget/looker/models"
  
  
)

// AllDashboardsReader is a Reader for the AllDashboards structure.
type AllDashboardsReader struct {
  formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *AllDashboardsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
  switch response.Code() {
  
    case 200:
      result := NewAllDashboardsOK()
      if err := result.readResponse(response, consumer, o.formats); err != nil {
        return nil, err
      }
      return result, nil
  
    case 400:
      result := NewAllDashboardsBadRequest()
      if err := result.readResponse(response, consumer, o.formats); err != nil {
        return nil, err
      }
      return nil, result
  
    case 404:
      result := NewAllDashboardsNotFound()
      if err := result.readResponse(response, consumer, o.formats); err != nil {
        return nil, err
      }
      return nil, result
  
    default:
      return nil, runtime.NewAPIError("unknown error", response, response.Code())
  }
}


// NewAllDashboardsOK creates a AllDashboardsOK with default headers values
func NewAllDashboardsOK() *AllDashboardsOK {
  return &AllDashboardsOK{
    }
}

/*AllDashboardsOK handles this case with default header values.

dashboards
*/
type AllDashboardsOK struct {
  
  
  Payload []
  
}


func (o *AllDashboardsOK) Error() string {
	return fmt.Sprintf("[GET /dashboards][%d] allDashboardsOK  %+v", 200, o.Payload)
}


func (o *AllDashboardsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
  
  
  
  // response payload
  if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
    return err
  }
  
  return nil
}


// NewAllDashboardsBadRequest creates a AllDashboardsBadRequest with default headers values
func NewAllDashboardsBadRequest() *AllDashboardsBadRequest {
  return &AllDashboardsBadRequest{
    }
}

/*AllDashboardsBadRequest handles this case with default header values.

Bad Request
*/
type AllDashboardsBadRequest struct {
  
  
  Payload 
  
}


func (o *AllDashboardsBadRequest) Error() string {
	return fmt.Sprintf("[GET /dashboards][%d] allDashboardsBadRequest  %+v", 400, o.Payload)
}


func (o *AllDashboardsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
  
  
  
  // response payload
  if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
    return err
  }
  
  return nil
}


// NewAllDashboardsNotFound creates a AllDashboardsNotFound with default headers values
func NewAllDashboardsNotFound() *AllDashboardsNotFound {
  return &AllDashboardsNotFound{
    }
}

/*AllDashboardsNotFound handles this case with default header values.

Not Found
*/
type AllDashboardsNotFound struct {
  
  
  Payload 
  
}


func (o *AllDashboardsNotFound) Error() string {
	return fmt.Sprintf("[GET /dashboards][%d] allDashboardsNotFound  %+v", 404, o.Payload)
}


func (o *AllDashboardsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
  
  
  
  // response payload
  if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
    return err
  }
  
  return nil
}





