package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DashboardsMovePlanReader is a Reader for the DashboardsMovePlan structure.
type DashboardsMovePlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DashboardsMovePlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDashboardsMovePlanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDashboardsMovePlanBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDashboardsMovePlanNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDashboardsMovePlanOK creates a DashboardsMovePlanOK with default headers values
func NewDashboardsMovePlanOK() *DashboardsMovePlanOK {
	return &DashboardsMovePlanOK{}
}

/*DashboardsMovePlanOK handles this case with default header values.

dashboard
*/
type DashboardsMovePlanOK struct {
	Payload
}

func (o *DashboardsMovePlanOK) Error() string {
	return fmt.Sprintf("[GET /dashboards/move_plan][%d] dashboardsMovePlanOK  %+v", 200, o.Payload)
}

func (o *DashboardsMovePlanOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDashboardsMovePlanBadRequest creates a DashboardsMovePlanBadRequest with default headers values
func NewDashboardsMovePlanBadRequest() *DashboardsMovePlanBadRequest {
	return &DashboardsMovePlanBadRequest{}
}

/*DashboardsMovePlanBadRequest handles this case with default header values.

Bad Request
*/
type DashboardsMovePlanBadRequest struct {
	Payload
}

func (o *DashboardsMovePlanBadRequest) Error() string {
	return fmt.Sprintf("[GET /dashboards/move_plan][%d] dashboardsMovePlanBadRequest  %+v", 400, o.Payload)
}

func (o *DashboardsMovePlanBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDashboardsMovePlanNotFound creates a DashboardsMovePlanNotFound with default headers values
func NewDashboardsMovePlanNotFound() *DashboardsMovePlanNotFound {
	return &DashboardsMovePlanNotFound{}
}

/*DashboardsMovePlanNotFound handles this case with default header values.

Not Found
*/
type DashboardsMovePlanNotFound struct {
	Payload
}

func (o *DashboardsMovePlanNotFound) Error() string {
	return fmt.Sprintf("[GET /dashboards/move_plan][%d] dashboardsMovePlanNotFound  %+v", 404, o.Payload)
}

func (o *DashboardsMovePlanNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
