package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDashboardParams creates a new DeleteDashboardParams object
// with the default values initialized.
func NewDeleteDashboardParams() *DeleteDashboardParams {
	var ()
	return &DeleteDashboardParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDashboardParamsWithTimeout creates a new DeleteDashboardParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDashboardParamsWithTimeout(timeout time.Duration) *DeleteDashboardParams {
	var ()
	return &DeleteDashboardParams{

		timeout: timeout,
	}
}

/*DeleteDashboardParams contains all the parameters to send to the API endpoint
for the delete dashboard operation typically these are written to a http.Request
*/
type DeleteDashboardParams struct {

	/*DashboardID
	  Id of dashboard

	*/
	DashboardID string

	timeout time.Duration
}

// WithDashboardID adds the dashboardId to the delete dashboard params
func (o *DeleteDashboardParams) WithDashboardID(DashboardID string) *DeleteDashboardParams {
	o.DashboardID = DashboardID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDashboardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param dashboard_id
	if err := r.SetPathParam("dashboard_id", o.DashboardID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
