package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMoveDashboardsParams creates a new MoveDashboardsParams object
// with the default values initialized.
func NewMoveDashboardsParams() *MoveDashboardsParams {
	var ()
	return &MoveDashboardsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMoveDashboardsParamsWithTimeout creates a new MoveDashboardsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMoveDashboardsParamsWithTimeout(timeout time.Duration) *MoveDashboardsParams {
	var ()
	return &MoveDashboardsParams{

		timeout: timeout,
	}
}

/*MoveDashboardsParams contains all the parameters to send to the API endpoint
for the move dashboards operation typically these are written to a http.Request
*/
type MoveDashboardsParams struct {

	/*Body
	  dashboard

	*/
	Body
	/*DashboardIds
	  Dashboard ids to move.

	*/
	DashboardIds []string
	/*SpaceID
	  Destination space id.

	*/
	SpaceID *string

	timeout time.Duration
}

// WithBody adds the body to the move dashboards params
func (o *MoveDashboardsParams) WithBody(Body) *MoveDashboardsParams {
	o.Body = Body
	return o
}

// WithDashboardIds adds the dashboardIds to the move dashboards params
func (o *MoveDashboardsParams) WithDashboardIds(DashboardIds []string) *MoveDashboardsParams {
	o.DashboardIds = DashboardIds
	return o
}

// WithSpaceID adds the spaceId to the move dashboards params
func (o *MoveDashboardsParams) WithSpaceID(SpaceID *string) *MoveDashboardsParams {
	o.SpaceID = SpaceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *MoveDashboardsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	valuesDashboardIds := o.DashboardIds

	joinedDashboardIds := swag.JoinByFormat(valuesDashboardIds, "")
	// query array param dashboard_ids
	if err := r.SetQueryParam("dashboard_ids", joinedDashboardIds...); err != nil {
		return err
	}

	if o.SpaceID != nil {

		// query param space_id
		var qrSpaceID string
		if o.SpaceID != nil {
			qrSpaceID = *o.SpaceID
		}
		qSpaceID := qrSpaceID
		if qSpaceID != "" {
			if err := r.SetQueryParam("space_id", qSpaceID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
