package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAllRolesParams creates a new AllRolesParams object
// with the default values initialized.
func NewAllRolesParams() *AllRolesParams {
	var ()
	return &AllRolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAllRolesParamsWithTimeout creates a new AllRolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAllRolesParamsWithTimeout(timeout time.Duration) *AllRolesParams {
	var ()
	return &AllRolesParams{

		timeout: timeout,
	}
}

/*AllRolesParams contains all the parameters to send to the API endpoint
for the all roles operation typically these are written to a http.Request
*/
type AllRolesParams struct {

	/*Fields
	  Requested fields.

	*/
	Fields *string

	timeout time.Duration
}

// WithFields adds the fields to the all roles params
func (o *AllRolesParams) WithFields(Fields *string) *AllRolesParams {
	o.Fields = Fields
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *AllRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
