package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateModelSetParams creates a new CreateModelSetParams object
// with the default values initialized.
func NewCreateModelSetParams() *CreateModelSetParams {
	var ()
	return &CreateModelSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateModelSetParamsWithTimeout creates a new CreateModelSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateModelSetParamsWithTimeout(timeout time.Duration) *CreateModelSetParams {
	var ()
	return &CreateModelSetParams{

		timeout: timeout,
	}
}

/*CreateModelSetParams contains all the parameters to send to the API endpoint
for the create model set operation typically these are written to a http.Request
*/
type CreateModelSetParams struct {

	/*Body
	  ModelSet

	*/
	Body

	timeout time.Duration
}

// WithBody adds the body to the create model set params
func (o *CreateModelSetParams) WithBody(Body) *CreateModelSetParams {
	o.Body = Body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateModelSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
