package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePermissionSetParams creates a new DeletePermissionSetParams object
// with the default values initialized.
func NewDeletePermissionSetParams() *DeletePermissionSetParams {
	var ()
	return &DeletePermissionSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePermissionSetParamsWithTimeout creates a new DeletePermissionSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePermissionSetParamsWithTimeout(timeout time.Duration) *DeletePermissionSetParams {
	var ()
	return &DeletePermissionSetParams{

		timeout: timeout,
	}
}

/*DeletePermissionSetParams contains all the parameters to send to the API endpoint
for the delete permission set operation typically these are written to a http.Request
*/
type DeletePermissionSetParams struct {

	/*PermissionSetID
	  Id of permission set

	*/
	PermissionSetID int64

	timeout time.Duration
}

// WithPermissionSetID adds the permissionSetId to the delete permission set params
func (o *DeletePermissionSetParams) WithPermissionSetID(PermissionSetID int64) *DeletePermissionSetParams {
	o.PermissionSetID = PermissionSetID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePermissionSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param permission_set_id
	if err := r.SetPathParam("permission_set_id", swag.FormatInt64(o.PermissionSetID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
