package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRoleParams creates a new DeleteRoleParams object
// with the default values initialized.
func NewDeleteRoleParams() *DeleteRoleParams {
	var ()
	return &DeleteRoleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRoleParamsWithTimeout creates a new DeleteRoleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRoleParamsWithTimeout(timeout time.Duration) *DeleteRoleParams {
	var ()
	return &DeleteRoleParams{

		timeout: timeout,
	}
}

/*DeleteRoleParams contains all the parameters to send to the API endpoint
for the delete role operation typically these are written to a http.Request
*/
type DeleteRoleParams struct {

	/*RoleID
	  id of role

	*/
	RoleID int64

	timeout time.Duration
}

// WithRoleID adds the roleId to the delete role params
func (o *DeleteRoleParams) WithRoleID(RoleID int64) *DeleteRoleParams {
	o.RoleID = RoleID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param role_id
	if err := r.SetPathParam("role_id", swag.FormatInt64(o.RoleID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
