package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteModelSetParams creates a new DeleteModelSetParams object
// with the default values initialized.
func NewDeleteModelSetParams() *DeleteModelSetParams {
	var ()
	return &DeleteModelSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteModelSetParamsWithTimeout creates a new DeleteModelSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteModelSetParamsWithTimeout(timeout time.Duration) *DeleteModelSetParams {
	var ()
	return &DeleteModelSetParams{

		timeout: timeout,
	}
}

/*DeleteModelSetParams contains all the parameters to send to the API endpoint
for the delete model set operation typically these are written to a http.Request
*/
type DeleteModelSetParams struct {

	/*ModelSetID
	  id of model set

	*/
	ModelSetID int64

	timeout time.Duration
}

// WithModelSetID adds the modelSetId to the delete model set params
func (o *DeleteModelSetParams) WithModelSetID(ModelSetID int64) *DeleteModelSetParams {
	o.ModelSetID = ModelSetID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteModelSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param model_set_id
	if err := r.SetPathParam("model_set_id", swag.FormatInt64(o.ModelSetID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
