package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPermissionSetParams creates a new PermissionSetParams object
// with the default values initialized.
func NewPermissionSetParams() *PermissionSetParams {
	var ()
	return &PermissionSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPermissionSetParamsWithTimeout creates a new PermissionSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPermissionSetParamsWithTimeout(timeout time.Duration) *PermissionSetParams {
	var ()
	return &PermissionSetParams{

		timeout: timeout,
	}
}

/*PermissionSetParams contains all the parameters to send to the API endpoint
for the permission set operation typically these are written to a http.Request
*/
type PermissionSetParams struct {

	/*Fields
	  Requested fields.

	*/
	Fields *string
	/*PermissionSetID
	  Id of permission set

	*/
	PermissionSetID int64

	timeout time.Duration
}

// WithFields adds the fields to the permission set params
func (o *PermissionSetParams) WithFields(Fields *string) *PermissionSetParams {
	o.Fields = Fields
	return o
}

// WithPermissionSetID adds the permissionSetId to the permission set params
func (o *PermissionSetParams) WithPermissionSetID(PermissionSetID int64) *PermissionSetParams {
	o.PermissionSetID = PermissionSetID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PermissionSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param permission_set_id
	if err := r.SetPathParam("permission_set_id", swag.FormatInt64(o.PermissionSetID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
