package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetRoleUsersParams creates a new SetRoleUsersParams object
// with the default values initialized.
func NewSetRoleUsersParams() *SetRoleUsersParams {
	var ()
	return &SetRoleUsersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetRoleUsersParamsWithTimeout creates a new SetRoleUsersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetRoleUsersParamsWithTimeout(timeout time.Duration) *SetRoleUsersParams {
	var ()
	return &SetRoleUsersParams{

		timeout: timeout,
	}
}

/*SetRoleUsersParams contains all the parameters to send to the API endpoint
for the set role users operation typically these are written to a http.Request
*/
type SetRoleUsersParams struct {

	/*Body
	  array of user ids for role

	*/
	Body []int64
	/*RoleID
	  id of role

	*/
	RoleID int64

	timeout time.Duration
}

// WithBody adds the body to the set role users params
func (o *SetRoleUsersParams) WithBody(Body []int64) *SetRoleUsersParams {
	o.Body = Body
	return o
}

// WithRoleID adds the roleId to the set role users params
func (o *SetRoleUsersParams) WithRoleID(RoleID int64) *SetRoleUsersParams {
	o.RoleID = RoleID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *SetRoleUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param role_id
	if err := r.SetPathParam("role_id", swag.FormatInt64(o.RoleID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
