package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateRoleParams creates a new UpdateRoleParams object
// with the default values initialized.
func NewUpdateRoleParams() *UpdateRoleParams {
	var ()
	return &UpdateRoleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRoleParamsWithTimeout creates a new UpdateRoleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRoleParamsWithTimeout(timeout time.Duration) *UpdateRoleParams {
	var ()
	return &UpdateRoleParams{

		timeout: timeout,
	}
}

/*UpdateRoleParams contains all the parameters to send to the API endpoint
for the update role operation typically these are written to a http.Request
*/
type UpdateRoleParams struct {

	/*Body
	  Role

	*/
	Body
	/*RoleID
	  id of role

	*/
	RoleID int64

	timeout time.Duration
}

// WithBody adds the body to the update role params
func (o *UpdateRoleParams) WithBody(Body) *UpdateRoleParams {
	o.Body = Body
	return o
}

// WithRoleID adds the roleId to the update role params
func (o *UpdateRoleParams) WithRoleID(RoleID int64) *UpdateRoleParams {
	o.RoleID = RoleID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param role_id
	if err := r.SetPathParam("role_id", swag.FormatInt64(o.RoleID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
