package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdatePermissionSetParams creates a new UpdatePermissionSetParams object
// with the default values initialized.
func NewUpdatePermissionSetParams() *UpdatePermissionSetParams {
	var ()
	return &UpdatePermissionSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePermissionSetParamsWithTimeout creates a new UpdatePermissionSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdatePermissionSetParamsWithTimeout(timeout time.Duration) *UpdatePermissionSetParams {
	var ()
	return &UpdatePermissionSetParams{

		timeout: timeout,
	}
}

/*UpdatePermissionSetParams contains all the parameters to send to the API endpoint
for the update permission set operation typically these are written to a http.Request
*/
type UpdatePermissionSetParams struct {

	/*Body
	  PermissionSet

	*/
	Body
	/*PermissionSetID
	  id of permission set

	*/
	PermissionSetID int64

	timeout time.Duration
}

// WithBody adds the body to the update permission set params
func (o *UpdatePermissionSetParams) WithBody(Body) *UpdatePermissionSetParams {
	o.Body = Body
	return o
}

// WithPermissionSetID adds the permissionSetId to the update permission set params
func (o *UpdatePermissionSetParams) WithPermissionSetID(PermissionSetID int64) *UpdatePermissionSetParams {
	o.PermissionSetID = PermissionSetID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePermissionSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param permission_set_id
	if err := r.SetPathParam("permission_set_id", swag.FormatInt64(o.PermissionSetID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
