package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateModelSetParams creates a new UpdateModelSetParams object
// with the default values initialized.
func NewUpdateModelSetParams() *UpdateModelSetParams {
	var ()
	return &UpdateModelSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateModelSetParamsWithTimeout creates a new UpdateModelSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateModelSetParamsWithTimeout(timeout time.Duration) *UpdateModelSetParams {
	var ()
	return &UpdateModelSetParams{

		timeout: timeout,
	}
}

/*UpdateModelSetParams contains all the parameters to send to the API endpoint
for the update model set operation typically these are written to a http.Request
*/
type UpdateModelSetParams struct {

	/*Body
	  ModelSet

	*/
	Body
	/*ModelSetID
	  id of model set

	*/
	ModelSetID int64

	timeout time.Duration
}

// WithBody adds the body to the update model set params
func (o *UpdateModelSetParams) WithBody(Body) *UpdateModelSetParams {
	o.Body = Body
	return o
}

// WithModelSetID adds the modelSetId to the update model set params
func (o *UpdateModelSetParams) WithModelSetID(ModelSetID int64) *UpdateModelSetParams {
	o.ModelSetID = ModelSetID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateModelSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param model_set_id
	if err := r.SetPathParam("model_set_id", swag.FormatInt64(o.ModelSetID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
