package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateQueryReader is a Reader for the CreateQuery structure.
type CreateQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateQueryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreateQueryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateQueryOK creates a CreateQueryOK with default headers values
func NewCreateQueryOK() *CreateQueryOK {
	return &CreateQueryOK{}
}

/*CreateQueryOK handles this case with default header values.

query
*/
type CreateQueryOK struct {
	Payload
}

func (o *CreateQueryOK) Error() string {
	return fmt.Sprintf("[POST /queries][%d] createQueryOK  %+v", 200, o.Payload)
}

func (o *CreateQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateQueryBadRequest creates a CreateQueryBadRequest with default headers values
func NewCreateQueryBadRequest() *CreateQueryBadRequest {
	return &CreateQueryBadRequest{}
}

/*CreateQueryBadRequest handles this case with default header values.

Bad Request
*/
type CreateQueryBadRequest struct {
	Payload
}

func (o *CreateQueryBadRequest) Error() string {
	return fmt.Sprintf("[POST /queries][%d] createQueryBadRequest  %+v", 400, o.Payload)
}

func (o *CreateQueryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateQueryNotFound creates a CreateQueryNotFound with default headers values
func NewCreateQueryNotFound() *CreateQueryNotFound {
	return &CreateQueryNotFound{}
}

/*CreateQueryNotFound handles this case with default header values.

Not Found
*/
type CreateQueryNotFound struct {
	Payload
}

func (o *CreateQueryNotFound) Error() string {
	return fmt.Sprintf("[POST /queries][%d] createQueryNotFound  %+v", 404, o.Payload)
}

func (o *CreateQueryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
