package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewQueryParams creates a new QueryParams object
// with the default values initialized.
func NewQueryParams() *QueryParams {
	var ()
	return &QueryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewQueryParamsWithTimeout creates a new QueryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewQueryParamsWithTimeout(timeout time.Duration) *QueryParams {
	var ()
	return &QueryParams{

		timeout: timeout,
	}
}

/*QueryParams contains all the parameters to send to the API endpoint
for the query operation typically these are written to a http.Request
*/
type QueryParams struct {

	/*Fields
	  Requested fields.

	*/
	Fields *string
	/*QueryID
	  Id of query

	*/
	QueryID int64

	timeout time.Duration
}

// WithFields adds the fields to the query params
func (o *QueryParams) WithFields(Fields *string) *QueryParams {
	o.Fields = Fields
	return o
}

// WithQueryID adds the queryId to the query params
func (o *QueryParams) WithQueryID(QueryID int64) *QueryParams {
	o.QueryID = QueryID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *QueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param query_id
	if err := r.SetPathParam("query_id", swag.FormatInt64(o.QueryID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
