package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// QueryReader is a Reader for the Query structure.
type QueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *QueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewQueryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewQueryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewQueryOK creates a QueryOK with default headers values
func NewQueryOK() *QueryOK {
	return &QueryOK{}
}

/*QueryOK handles this case with default header values.

query
*/
type QueryOK struct {
	Payload
}

func (o *QueryOK) Error() string {
	return fmt.Sprintf("[GET /queries/{query_id}][%d] queryOK  %+v", 200, o.Payload)
}

func (o *QueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryBadRequest creates a QueryBadRequest with default headers values
func NewQueryBadRequest() *QueryBadRequest {
	return &QueryBadRequest{}
}

/*QueryBadRequest handles this case with default header values.

Bad Request
*/
type QueryBadRequest struct {
	Payload
}

func (o *QueryBadRequest) Error() string {
	return fmt.Sprintf("[GET /queries/{query_id}][%d] queryBadRequest  %+v", 400, o.Payload)
}

func (o *QueryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryNotFound creates a QueryNotFound with default headers values
func NewQueryNotFound() *QueryNotFound {
	return &QueryNotFound{}
}

/*QueryNotFound handles this case with default header values.

Not Found
*/
type QueryNotFound struct {
	Payload
}

func (o *QueryNotFound) Error() string {
	return fmt.Sprintf("[GET /queries/{query_id}][%d] queryNotFound  %+v", 404, o.Payload)
}

func (o *QueryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
