package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RunQueryReader is a Reader for the RunQuery structure.
type RunQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *RunQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRunQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewRunQueryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewRunQueryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRunQueryOK creates a RunQueryOK with default headers values
func NewRunQueryOK() *RunQueryOK {
	return &RunQueryOK{}
}

/*RunQueryOK handles this case with default header values.

query
*/
type RunQueryOK struct {
	Payload string
}

func (o *RunQueryOK) Error() string {
	return fmt.Sprintf("[GET /queries/{query_id}/run/{format}][%d] runQueryOK  %+v", 200, o.Payload)
}

func (o *RunQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunQueryBadRequest creates a RunQueryBadRequest with default headers values
func NewRunQueryBadRequest() *RunQueryBadRequest {
	return &RunQueryBadRequest{}
}

/*RunQueryBadRequest handles this case with default header values.

Bad Request
*/
type RunQueryBadRequest struct {
	Payload
}

func (o *RunQueryBadRequest) Error() string {
	return fmt.Sprintf("[GET /queries/{query_id}/run/{format}][%d] runQueryBadRequest  %+v", 400, o.Payload)
}

func (o *RunQueryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunQueryNotFound creates a RunQueryNotFound with default headers values
func NewRunQueryNotFound() *RunQueryNotFound {
	return &RunQueryNotFound{}
}

/*RunQueryNotFound handles this case with default header values.

Not Found
*/
type RunQueryNotFound struct {
	Payload
}

func (o *RunQueryNotFound) Error() string {
	return fmt.Sprintf("[GET /queries/{query_id}/run/{format}][%d] runQueryNotFound  %+v", 404, o.Payload)
}

func (o *RunQueryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
