package running_queries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewKillQueryParams creates a new KillQueryParams object
// with the default values initialized.
func NewKillQueryParams() *KillQueryParams {
	var ()
	return &KillQueryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewKillQueryParamsWithTimeout creates a new KillQueryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewKillQueryParamsWithTimeout(timeout time.Duration) *KillQueryParams {
	var ()
	return &KillQueryParams{

		timeout: timeout,
	}
}

/*KillQueryParams contains all the parameters to send to the API endpoint
for the kill query operation typically these are written to a http.Request
*/
type KillQueryParams struct {

	/*QuerySlug
	  query slug

	*/
	QuerySlug string

	timeout time.Duration
}

// WithQuerySlug adds the querySlug to the kill query params
func (o *KillQueryParams) WithQuerySlug(QuerySlug string) *KillQueryParams {
	o.QuerySlug = QuerySlug
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *KillQueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param query_slug
	if err := r.SetPathParam("query_slug", o.QuerySlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
