package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteUserCredentialsTotpParams creates a new DeleteUserCredentialsTotpParams object
// with the default values initialized.
func NewDeleteUserCredentialsTotpParams() *DeleteUserCredentialsTotpParams {
	var ()
	return &DeleteUserCredentialsTotpParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserCredentialsTotpParamsWithTimeout creates a new DeleteUserCredentialsTotpParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUserCredentialsTotpParamsWithTimeout(timeout time.Duration) *DeleteUserCredentialsTotpParams {
	var ()
	return &DeleteUserCredentialsTotpParams{

		timeout: timeout,
	}
}

/*DeleteUserCredentialsTotpParams contains all the parameters to send to the API endpoint
for the delete user credentials totp operation typically these are written to a http.Request
*/
type DeleteUserCredentialsTotpParams struct {

	/*UserID
	  id of user

	*/
	UserID int64

	timeout time.Duration
}

// WithUserID adds the userId to the delete user credentials totp params
func (o *DeleteUserCredentialsTotpParams) WithUserID(UserID int64) *DeleteUserCredentialsTotpParams {
	o.UserID = UserID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserCredentialsTotpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
