package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMeParams creates a new MeParams object
// with the default values initialized.
func NewMeParams() *MeParams {
	var ()
	return &MeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMeParamsWithTimeout creates a new MeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMeParamsWithTimeout(timeout time.Duration) *MeParams {
	var ()
	return &MeParams{

		timeout: timeout,
	}
}

/*MeParams contains all the parameters to send to the API endpoint
for the me operation typically these are written to a http.Request
*/
type MeParams struct {

	/*Fields
	  Requested fields.

	*/
	Fields *string

	timeout time.Duration
}

// WithFields adds the fields to the me params
func (o *MeParams) WithFields(Fields *string) *MeParams {
	o.Fields = Fields
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *MeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
