package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateUserAccessFilterParams creates a new UpdateUserAccessFilterParams object
// with the default values initialized.
func NewUpdateUserAccessFilterParams() *UpdateUserAccessFilterParams {
	var ()
	return &UpdateUserAccessFilterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateUserAccessFilterParamsWithTimeout creates a new UpdateUserAccessFilterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateUserAccessFilterParamsWithTimeout(timeout time.Duration) *UpdateUserAccessFilterParams {
	var ()
	return &UpdateUserAccessFilterParams{

		timeout: timeout,
	}
}

/*UpdateUserAccessFilterParams contains all the parameters to send to the API endpoint
for the update user access filter operation typically these are written to a http.Request
*/
type UpdateUserAccessFilterParams struct {

	/*AccessFilterID
	  id of Access filter

	*/
	AccessFilterID int64
	/*Body
	  Access filter

	*/
	Body
	/*Fields
	  Requested fields.

	*/
	Fields *string
	/*UserID
	  id of user

	*/
	UserID int64

	timeout time.Duration
}

// WithAccessFilterID adds the accessFilterId to the update user access filter params
func (o *UpdateUserAccessFilterParams) WithAccessFilterID(AccessFilterID int64) *UpdateUserAccessFilterParams {
	o.AccessFilterID = AccessFilterID
	return o
}

// WithBody adds the body to the update user access filter params
func (o *UpdateUserAccessFilterParams) WithBody(Body) *UpdateUserAccessFilterParams {
	o.Body = Body
	return o
}

// WithFields adds the fields to the update user access filter params
func (o *UpdateUserAccessFilterParams) WithFields(Fields *string) *UpdateUserAccessFilterParams {
	o.Fields = Fields
	return o
}

// WithUserID adds the userId to the update user access filter params
func (o *UpdateUserAccessFilterParams) WithUserID(UserID int64) *UpdateUserAccessFilterParams {
	o.UserID = UserID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateUserAccessFilterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param access_filter_id
	if err := r.SetPathParam("access_filter_id", swag.FormatInt64(o.AccessFilterID)); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param user_id
	if err := r.SetPathParam("user_id", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
