package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateUserAccessFilterReader is a Reader for the UpdateUserAccessFilter structure.
type UpdateUserAccessFilterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *UpdateUserAccessFilterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateUserAccessFilterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateUserAccessFilterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewUpdateUserAccessFilterNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateUserAccessFilterOK creates a UpdateUserAccessFilterOK with default headers values
func NewUpdateUserAccessFilterOK() *UpdateUserAccessFilterOK {
	return &UpdateUserAccessFilterOK{}
}

/*UpdateUserAccessFilterOK handles this case with default header values.

Access filter
*/
type UpdateUserAccessFilterOK struct {
	Payload
}

func (o *UpdateUserAccessFilterOK) Error() string {
	return fmt.Sprintf("[PATCH /users/{user_id}/access_filters/{access_filter_id}][%d] updateUserAccessFilterOK  %+v", 200, o.Payload)
}

func (o *UpdateUserAccessFilterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateUserAccessFilterBadRequest creates a UpdateUserAccessFilterBadRequest with default headers values
func NewUpdateUserAccessFilterBadRequest() *UpdateUserAccessFilterBadRequest {
	return &UpdateUserAccessFilterBadRequest{}
}

/*UpdateUserAccessFilterBadRequest handles this case with default header values.

Bad Request
*/
type UpdateUserAccessFilterBadRequest struct {
	Payload
}

func (o *UpdateUserAccessFilterBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /users/{user_id}/access_filters/{access_filter_id}][%d] updateUserAccessFilterBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateUserAccessFilterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateUserAccessFilterNotFound creates a UpdateUserAccessFilterNotFound with default headers values
func NewUpdateUserAccessFilterNotFound() *UpdateUserAccessFilterNotFound {
	return &UpdateUserAccessFilterNotFound{}
}

/*UpdateUserAccessFilterNotFound handles this case with default header values.

Not Found
*/
type UpdateUserAccessFilterNotFound struct {
	Payload
}

func (o *UpdateUserAccessFilterNotFound) Error() string {
	return fmt.Sprintf("[PATCH /users/{user_id}/access_filters/{access_filter_id}][%d] updateUserAccessFilterNotFound  %+v", 404, o.Payload)
}

func (o *UpdateUserAccessFilterNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
