package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserCredentialsSamlReader is a Reader for the UserCredentialsSaml structure.
type UserCredentialsSamlReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *UserCredentialsSamlReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserCredentialsSamlOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUserCredentialsSamlBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewUserCredentialsSamlNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserCredentialsSamlOK creates a UserCredentialsSamlOK with default headers values
func NewUserCredentialsSamlOK() *UserCredentialsSamlOK {
	return &UserCredentialsSamlOK{}
}

/*UserCredentialsSamlOK handles this case with default header values.

Saml auth credential
*/
type UserCredentialsSamlOK struct {
	Payload
}

func (o *UserCredentialsSamlOK) Error() string {
	return fmt.Sprintf("[GET /users/{user_id}/credentials_saml][%d] userCredentialsSamlOK  %+v", 200, o.Payload)
}

func (o *UserCredentialsSamlOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserCredentialsSamlBadRequest creates a UserCredentialsSamlBadRequest with default headers values
func NewUserCredentialsSamlBadRequest() *UserCredentialsSamlBadRequest {
	return &UserCredentialsSamlBadRequest{}
}

/*UserCredentialsSamlBadRequest handles this case with default header values.

Bad Request
*/
type UserCredentialsSamlBadRequest struct {
	Payload
}

func (o *UserCredentialsSamlBadRequest) Error() string {
	return fmt.Sprintf("[GET /users/{user_id}/credentials_saml][%d] userCredentialsSamlBadRequest  %+v", 400, o.Payload)
}

func (o *UserCredentialsSamlBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserCredentialsSamlNotFound creates a UserCredentialsSamlNotFound with default headers values
func NewUserCredentialsSamlNotFound() *UserCredentialsSamlNotFound {
	return &UserCredentialsSamlNotFound{}
}

/*UserCredentialsSamlNotFound handles this case with default header values.

Not Found
*/
type UserCredentialsSamlNotFound struct {
	Payload
}

func (o *UserCredentialsSamlNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{user_id}/credentials_saml][%d] userCredentialsSamlNotFound  %+v", 404, o.Payload)
}

func (o *UserCredentialsSamlNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
