package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUserCredentialsEmbedParams creates a new UserCredentialsEmbedParams object
// with the default values initialized.
func NewUserCredentialsEmbedParams() *UserCredentialsEmbedParams {
	var ()
	return &UserCredentialsEmbedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserCredentialsEmbedParamsWithTimeout creates a new UserCredentialsEmbedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserCredentialsEmbedParamsWithTimeout(timeout time.Duration) *UserCredentialsEmbedParams {
	var ()
	return &UserCredentialsEmbedParams{

		timeout: timeout,
	}
}

/*UserCredentialsEmbedParams contains all the parameters to send to the API endpoint
for the user credentials embed operation typically these are written to a http.Request
*/
type UserCredentialsEmbedParams struct {

	/*CredentialsEmbedID
	  Id of Embedding credential

	*/
	CredentialsEmbedID int64
	/*Fields
	  Requested fields.

	*/
	Fields *string
	/*UserID
	  Id of user

	*/
	UserID int64

	timeout time.Duration
}

// WithCredentialsEmbedID adds the credentialsEmbedId to the user credentials embed params
func (o *UserCredentialsEmbedParams) WithCredentialsEmbedID(CredentialsEmbedID int64) *UserCredentialsEmbedParams {
	o.CredentialsEmbedID = CredentialsEmbedID
	return o
}

// WithFields adds the fields to the user credentials embed params
func (o *UserCredentialsEmbedParams) WithFields(Fields *string) *UserCredentialsEmbedParams {
	o.Fields = Fields
	return o
}

// WithUserID adds the userId to the user credentials embed params
func (o *UserCredentialsEmbedParams) WithUserID(UserID int64) *UserCredentialsEmbedParams {
	o.UserID = UserID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UserCredentialsEmbedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param credentials_embed_id
	if err := r.SetPathParam("credentials_embed_id", swag.FormatInt64(o.CredentialsEmbedID)); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param user_id
	if err := r.SetPathParam("user_id", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
