package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUserAccessFilterParams creates a new UserAccessFilterParams object
// with the default values initialized.
func NewUserAccessFilterParams() *UserAccessFilterParams {
	var ()
	return &UserAccessFilterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserAccessFilterParamsWithTimeout creates a new UserAccessFilterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserAccessFilterParamsWithTimeout(timeout time.Duration) *UserAccessFilterParams {
	var ()
	return &UserAccessFilterParams{

		timeout: timeout,
	}
}

/*UserAccessFilterParams contains all the parameters to send to the API endpoint
for the user access filter operation typically these are written to a http.Request
*/
type UserAccessFilterParams struct {

	/*AccessFilterID
	  Id of Access filter

	*/
	AccessFilterID int64
	/*Fields
	  Requested fields.

	*/
	Fields *string
	/*UserID
	  Id of user

	*/
	UserID int64

	timeout time.Duration
}

// WithAccessFilterID adds the accessFilterId to the user access filter params
func (o *UserAccessFilterParams) WithAccessFilterID(AccessFilterID int64) *UserAccessFilterParams {
	o.AccessFilterID = AccessFilterID
	return o
}

// WithFields adds the fields to the user access filter params
func (o *UserAccessFilterParams) WithFields(Fields *string) *UserAccessFilterParams {
	o.Fields = Fields
	return o
}

// WithUserID adds the userId to the user access filter params
func (o *UserAccessFilterParams) WithUserID(UserID int64) *UserAccessFilterParams {
	o.UserID = UserID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UserAccessFilterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param access_filter_id
	if err := r.SetPathParam("access_filter_id", swag.FormatInt64(o.AccessFilterID)); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param user_id
	if err := r.SetPathParam("user_id", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
