package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSamlTestConfigParams creates a new DeleteSamlTestConfigParams object
// with the default values initialized.
func NewDeleteSamlTestConfigParams() *DeleteSamlTestConfigParams {
	var ()
	return &DeleteSamlTestConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSamlTestConfigParamsWithTimeout creates a new DeleteSamlTestConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSamlTestConfigParamsWithTimeout(timeout time.Duration) *DeleteSamlTestConfigParams {
	var ()
	return &DeleteSamlTestConfigParams{

		timeout: timeout,
	}
}

/*DeleteSamlTestConfigParams contains all the parameters to send to the API endpoint
for the delete saml test config operation typically these are written to a http.Request
*/
type DeleteSamlTestConfigParams struct {

	/*TestSlug
	  Slug of test config

	*/
	TestSlug string

	timeout time.Duration
}

// WithTestSlug adds the testSlug to the delete saml test config params
func (o *DeleteSamlTestConfigParams) WithTestSlug(TestSlug string) *DeleteSamlTestConfigParams {
	o.TestSlug = TestSlug
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSamlTestConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param test_slug
	if err := r.SetPathParam("test_slug", o.TestSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
