package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFetchAndParseSamlIdpMetadataParams creates a new FetchAndParseSamlIdpMetadataParams object
// with the default values initialized.
func NewFetchAndParseSamlIdpMetadataParams() *FetchAndParseSamlIdpMetadataParams {
	var ()
	return &FetchAndParseSamlIdpMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFetchAndParseSamlIdpMetadataParamsWithTimeout creates a new FetchAndParseSamlIdpMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFetchAndParseSamlIdpMetadataParamsWithTimeout(timeout time.Duration) *FetchAndParseSamlIdpMetadataParams {
	var ()
	return &FetchAndParseSamlIdpMetadataParams{

		timeout: timeout,
	}
}

/*FetchAndParseSamlIdpMetadataParams contains all the parameters to send to the API endpoint
for the fetch and parse saml idp metadata operation typically these are written to a http.Request
*/
type FetchAndParseSamlIdpMetadataParams struct {

	/*Body
	  SAML IdP metadata public url

	*/
	Body *string

	timeout time.Duration
}

// WithBody adds the body to the fetch and parse saml idp metadata params
func (o *FetchAndParseSamlIdpMetadataParams) WithBody(Body *string) *FetchAndParseSamlIdpMetadataParams {
	o.Body = Body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *FetchAndParseSamlIdpMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
