package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewParseSamlIdpMetadataParams creates a new ParseSamlIdpMetadataParams object
// with the default values initialized.
func NewParseSamlIdpMetadataParams() *ParseSamlIdpMetadataParams {
	var ()
	return &ParseSamlIdpMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewParseSamlIdpMetadataParamsWithTimeout creates a new ParseSamlIdpMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewParseSamlIdpMetadataParamsWithTimeout(timeout time.Duration) *ParseSamlIdpMetadataParams {
	var ()
	return &ParseSamlIdpMetadataParams{

		timeout: timeout,
	}
}

/*ParseSamlIdpMetadataParams contains all the parameters to send to the API endpoint
for the parse saml idp metadata operation typically these are written to a http.Request
*/
type ParseSamlIdpMetadataParams struct {

	/*Body
	  SAML IdP metadata xml

	*/
	Body *string

	timeout time.Duration
}

// WithBody adds the body to the parse saml idp metadata params
func (o *ParseSamlIdpMetadataParams) WithBody(Body *string) *ParseSamlIdpMetadataParams {
	o.Body = Body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ParseSamlIdpMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
