package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSamlTestConfigParams creates a new SamlTestConfigParams object
// with the default values initialized.
func NewSamlTestConfigParams() *SamlTestConfigParams {
	var ()
	return &SamlTestConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSamlTestConfigParamsWithTimeout creates a new SamlTestConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSamlTestConfigParamsWithTimeout(timeout time.Duration) *SamlTestConfigParams {
	var ()
	return &SamlTestConfigParams{

		timeout: timeout,
	}
}

/*SamlTestConfigParams contains all the parameters to send to the API endpoint
for the saml test config operation typically these are written to a http.Request
*/
type SamlTestConfigParams struct {

	/*TestSlug
	  Slug of test config

	*/
	TestSlug string

	timeout time.Duration
}

// WithTestSlug adds the testSlug to the saml test config params
func (o *SamlTestConfigParams) WithTestSlug(TestSlug string) *SamlTestConfigParams {
	o.TestSlug = TestSlug
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *SamlTestConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param test_slug
	if err := r.SetPathParam("test_slug", o.TestSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
