package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSamlConfigParams creates a new SamlConfigParams object
// with the default values initialized.
func NewSamlConfigParams() *SamlConfigParams {

	return &SamlConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSamlConfigParamsWithTimeout creates a new SamlConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSamlConfigParamsWithTimeout(timeout time.Duration) *SamlConfigParams {

	return &SamlConfigParams{

		timeout: timeout,
	}
}

/*SamlConfigParams contains all the parameters to send to the API endpoint
for the saml config operation typically these are written to a http.Request
*/
type SamlConfigParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *SamlConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
