package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTestLdapConfigConnectionParams creates a new TestLdapConfigConnectionParams object
// with the default values initialized.
func NewTestLdapConfigConnectionParams() *TestLdapConfigConnectionParams {
	var ()
	return &TestLdapConfigConnectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTestLdapConfigConnectionParamsWithTimeout creates a new TestLdapConfigConnectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTestLdapConfigConnectionParamsWithTimeout(timeout time.Duration) *TestLdapConfigConnectionParams {
	var ()
	return &TestLdapConfigConnectionParams{

		timeout: timeout,
	}
}

/*TestLdapConfigConnectionParams contains all the parameters to send to the API endpoint
for the test ldap config connection operation typically these are written to a http.Request
*/
type TestLdapConfigConnectionParams struct {

	/*Body
	  LDAP Config

	*/
	Body

	timeout time.Duration
}

// WithBody adds the body to the test ldap config connection params
func (o *TestLdapConfigConnectionParams) WithBody(Body) *TestLdapConfigConnectionParams {
	o.Body = Body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *TestLdapConfigConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
