package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new project API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for project API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ResetProjectToProduction resets a project to the version that is in production

### Reset a project with a specified ID to the version of the project that is in production.

**DANGER** this will delete any changes that have not been pushed to a remote repository.

*/
func (a *Client) ResetProjectToProduction(params *ResetProjectToProductionParams) (*ResetProjectToProductionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewResetProjectToProductionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "reset_project_to_production",
		Method:             "POST",
		PathPattern:        "/projects/{project_id}/reset_to_production",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ResetProjectToProductionReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ResetProjectToProductionOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
