package look

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLookParams creates a new LookParams object
// with the default values initialized.
func NewLookParams() *LookParams {
	var ()
	return &LookParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLookParamsWithTimeout creates a new LookParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLookParamsWithTimeout(timeout time.Duration) *LookParams {
	var ()
	return &LookParams{

		timeout: timeout,
	}
}

/*LookParams contains all the parameters to send to the API endpoint
for the look operation typically these are written to a http.Request
*/
type LookParams struct {

	/*Fields
	  Requested fields.

	*/
	Fields *string
	/*LookID
	  Id of look

	*/
	LookID int64

	timeout time.Duration
}

// WithFields adds the fields to the look params
func (o *LookParams) WithFields(Fields *string) *LookParams {
	o.Fields = Fields
	return o
}

// WithLookID adds the lookId to the look params
func (o *LookParams) WithLookID(LookID int64) *LookParams {
	o.LookID = LookID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *LookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param look_id
	if err := r.SetPathParam("look_id", swag.FormatInt64(o.LookID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
