package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*AsyncQuery async query

swagger:model AsyncQuery
*/
type AsyncQuery struct {

	/* Unique Id

	Read Only: true
	*/
	QueryTaskID string `json:"query_task_id,omitempty"`

	/* Estimated Runtime

	Read Only: true
	*/
	Runtime float64 `json:"runtime,omitempty"`
}

// Validate validates this async query
func (m *AsyncQuery) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
