package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*CredentialsLookerOpenid credentials looker openid

swagger:model CredentialsLookerOpenid
*/
type CredentialsLookerOpenid struct {

	/* Timestamp for the creation of this credential

	Read Only: true
	*/
	CreatedAt string `json:"created_at,omitempty"`

	/* EMail address used for user login

	Read Only: true
	*/
	Email string `json:"email,omitempty"`

	/* Has this credential been disabled?

	Read Only: true
	*/
	IsDisabled *bool `json:"is_disabled,omitempty"`

	/* Timestamp for most recent login using credential

	Read Only: true
	*/
	LoggedInAt string `json:"logged_in_at,omitempty"`

	/* IP address of client for most recent login using credential

	Read Only: true
	*/
	LoggedInIP string `json:"logged_in_ip,omitempty"`

	/* Short name for the type of this kind of credential

	Read Only: true
	*/
	Type string `json:"type,omitempty"`

	/* Link to get this item

	Read Only: true
	*/
	URL strfmt.URI `json:"url,omitempty"`

	/* Link to get this user

	Read Only: true
	*/
	UserURL strfmt.URI `json:"user_url,omitempty"`
}

// Validate validates this credentials looker openid
func (m *CredentialsLookerOpenid) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
