package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*DatafluxLook dataflux look

swagger:model DatafluxLook
*/
type DatafluxLook struct {

	/* Description
	 */
	Description string `json:"description,omitempty"`

	/* Embed Url

	Read Only: true
	*/
	EmbedURL string `json:"embed_url,omitempty"`

	/* Excel File Url

	Read Only: true
	*/
	ExcelFileURL string `json:"excel_file_url,omitempty"`

	/* Google Spreadsheet Formula

	Read Only: true
	*/
	GoogleSpreadsheetFormula string `json:"google_spreadsheet_formula,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID int64 `json:"id,omitempty"`

	/* Image Embed Url

	Read Only: true
	*/
	ImageEmbedURL string `json:"image_embed_url,omitempty"`

	/* Is Public
	 */
	Public bool `json:"public,omitempty"`

	/* Public Slug

	Read Only: true
	*/
	PublicSlug string `json:"public_slug,omitempty"`

	/* Public Url

	Read Only: true
	*/
	PublicURL string `json:"public_url,omitempty"`

	/* Query Id
	 */
	QueryID int64 `json:"query_id,omitempty"`

	/* Short Url

	Read Only: true
	*/
	ShortURL string `json:"short_url,omitempty"`

	/* (Write-only) Space Id
	 */
	SpaceID int64 `json:"space_id,omitempty"`

	/* Look Title
	 */
	Title string `json:"title,omitempty"`

	/* (Write-only) User Id
	 */
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this dataflux look
func (m *DatafluxLook) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
