package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*DatafluxDashboardElement dataflux dashboard element

swagger:model DatafluxDashboardElement
*/
type DatafluxDashboardElement struct {

	/* Text tile body text
	 */
	BodyText string `json:"body_text,omitempty"`

	/* Text tile body text as Html

	Read Only: true
	*/
	BodyTextAsHTML string `json:"body_text_as_html,omitempty"`

	/* Id of Dashboard

	Read Only: true
	*/
	DashboardID string `json:"dashboard_id,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID int64 `json:"id,omitempty"`

	/* Listen
	 */
	Listen string `json:"listen,omitempty"`

	/* Id Of Look
	 */
	LookID int64 `json:"look_id,omitempty"`

	/* Note Display
	 */
	NoteDisplay string `json:"note_display,omitempty"`

	/* Note State
	 */
	NoteState string `json:"note_state,omitempty"`

	/* Note Text
	 */
	NoteText string `json:"note_text,omitempty"`

	/* Note Text as Html

	Read Only: true
	*/
	NoteTextAsHTML string `json:"note_text_as_html,omitempty"`

	/* Refresh Interval
	 */
	RefreshInterval string `json:"refresh_interval,omitempty"`

	/* Refresh Interval as integer

	Read Only: true
	*/
	RefreshIntervalToI int64 `json:"refresh_interval_to_i,omitempty"`

	/* Text tile subtitle text
	 */
	SubtitleText string `json:"subtitle_text,omitempty"`

	/* Text tile title text
	 */
	TitleText string `json:"title_text,omitempty"`

	/* Type
	 */
	Type string `json:"type,omitempty"`
}

// Validate validates this dataflux dashboard element
func (m *DatafluxDashboardElement) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
