package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*DatafluxQueryTask dataflux query task

swagger:model DatafluxQueryTask
*/
type DatafluxQueryTask struct {

	/* Whether or not to use the cache

	Read Only: true
	*/
	Cache *bool `json:"cache,omitempty"`

	/* Retrieve any results from cache even if the results have expired.

	Read Only: true
	*/
	CacheOnly *bool `json:"cache_only,omitempty"`

	/* Use production models to run query (even is user is in dev mode).

	Read Only: true
	*/
	ForceProduction *bool `json:"force_production,omitempty"`

	/* whether or not to generate links in the query response.

	Read Only: true
	*/
	GenerateLinks *bool `json:"generate_links,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID string `json:"id,omitempty"`

	/* Prefix to use for drill links.

	Read Only: true
	*/
	PathPrefix string `json:"path_prefix,omitempty"`

	/* Id of query

	Read Only: true
	*/
	QueryID int64 `json:"query_id,omitempty"`

	/* ID of query task results used to reference results of the query (when complete).

	Read Only: true
	*/
	QueryResultID string `json:"query_result_id,omitempty"`

	/* Rebuild PDTS used in query.

	Read Only: true
	*/
	RebuildPdts *bool `json:"rebuild_pdts,omitempty"`

	/* Runtime of prior queries.

	Read Only: true
	*/
	Runtime float32 `json:"runtime,omitempty"`

	/* Status of query task.

	Read Only: true
	*/
	Status string `json:"status,omitempty"`
}

// Validate validates this dataflux query task
func (m *DatafluxQueryTask) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
