package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*DatafluxDashboard dataflux dashboard

swagger:model DatafluxDashboard
*/
type DatafluxDashboard struct {

	/* Background color
	 */
	BackgroundColor string `json:"background_color,omitempty"`

	/* Description
	 */
	Description string `json:"description,omitempty"`

	/* Is Hidden
	 */
	Hidden bool `json:"hidden,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID string `json:"id,omitempty"`

	/* configuration option that governs how dashboard loading will happen.
	 */
	LoadConfiguration string `json:"load_configuration,omitempty"`

	/* Is Read-only

	Read Only: true
	*/
	Readonly *bool `json:"readonly,omitempty"`

	/* Refresh Interval
	 */
	RefreshInterval string `json:"refresh_interval,omitempty"`

	/* Refresh Interval as Integer

	Read Only: true
	*/
	RefreshIntervalToI int64 `json:"refresh_interval_to_i,omitempty"`

	/* Show filters bar
	 */
	ShowFiltersBar bool `json:"show_filters_bar,omitempty"`

	/* Show tile shadow
	 */
	ShowTileShadow bool `json:"show_tile_shadow,omitempty"`

	/* Show title
	 */
	ShowTitle bool `json:"show_title,omitempty"`

	/* (Write-only) Id of Space
	 */
	SpaceID int64 `json:"space_id,omitempty"`

	/* Color of text on text tiles
	 */
	TextTileTextColor string `json:"text_tile_text_color,omitempty"`

	/* Tile background color
	 */
	TileBackgroundColor string `json:"tile_background_color,omitempty"`

	/* Tile border radius
	 */
	TileBorderRadius int64 `json:"tile_border_radius,omitempty"`

	/* Tile separator color
	 */
	TileSeparatorColor string `json:"tile_separator_color,omitempty"`

	/* Tile text color
	 */
	TileTextColor string `json:"tile_text_color,omitempty"`

	/* Look Title
	 */
	Title string `json:"title,omitempty"`

	/* Title color
	 */
	TitleColor string `json:"title_color,omitempty"`

	/* Id of User

	Read Only: true
	*/
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this dataflux dashboard
func (m *DatafluxDashboard) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
