package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*DatafluxSpace dataflux space

swagger:model DatafluxSpace
*/
type DatafluxSpace struct {

	/* User Id of Creator

	Read Only: true
	*/
	CreatorID int64 `json:"creator_id,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID string `json:"id,omitempty"`

	/* Space is a user's personal space
	 */
	IsPersonal bool `json:"is_personal,omitempty"`

	/* Unique Name

	Read Only: true
	*/
	Name string `json:"name,omitempty"`

	/* Id of Parent Space
	 */
	ParentID int64 `json:"parent_id,omitempty"`
}

// Validate validates this dataflux space
func (m *DatafluxSpace) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
