package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*DatafluxDashboardLayout dataflux dashboard layout

swagger:model DatafluxDashboardLayout
*/
type DatafluxDashboardLayout struct {

	/* Is Active
	 */
	Active bool `json:"active,omitempty"`

	/* Column Width
	 */
	ColumnWidth int64 `json:"column_width,omitempty"`

	/* Id of Dashboard

	Read Only: true
	*/
	DashboardID string `json:"dashboard_id,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID int64 `json:"id,omitempty"`

	/* Type
	 */
	Type string `json:"type,omitempty"`

	/* Width
	 */
	Width int64 `json:"width,omitempty"`
}

// Validate validates this dataflux dashboard layout
func (m *DatafluxDashboardLayout) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
