package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*DialectInfo dialect info

swagger:model DialectInfo
*/
type DialectInfo struct {

	/* Default number max connections

	Read Only: true
	*/
	DefaultMaxConnections string `json:"default_max_connections,omitempty"`

	/* Default port number

	Read Only: true
	*/
	DefaultPort string `json:"default_port,omitempty"`

	/* Is the supporting driver installed

	Read Only: true
	*/
	Installed *bool `json:"installed,omitempty"`

	/* The human-readable label of the connection

	Read Only: true
	*/
	Label string `json:"label,omitempty"`

	/* What the dialect calls the equivalent of a normal SQL table

	Read Only: true
	*/
	LabelForDatabaseEquivalent string `json:"label_for_database_equivalent,omitempty"`

	/* The name of the dialect

	Read Only: true
	*/
	Name string `json:"name,omitempty"`

	/* Option support details

	Read Only: true
	*/
	SupportedOptions `json:"supported_options,omitempty"`
}

// Validate validates this dialect info
func (m *DialectInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
