package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

/*LDAPGroupRead l d a p group read

swagger:model LDAPGroupRead
*/
type LDAPGroupRead struct {

	/* Name of group in LDAP

	Read Only: true
	*/
	Name string `json:"name,omitempty"`

	/* Looker Roles

	Read Only: true
	*/
	Roles []Role `json:"roles,omitempty"`

	/* Link to ldap config

	Read Only: true
	*/
	URL strfmt.URI `json:"url,omitempty"`
}

// Validate validates this l d a p group read
func (m *LDAPGroupRead) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRoles(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LDAPGroupRead) validateRoles(formats strfmt.Registry) error {

	if swag.IsZero(m.Roles) { // not required
		return nil
	}

	return nil
}
