package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*ModelSet model set

swagger:model ModelSet
*/
type ModelSet struct {

	/* all access

	Read Only: true
	*/
	AllAccess *bool `json:"all_access,omitempty"`

	/* built in

	Read Only: true
	*/
	BuiltIn *bool `json:"built_in,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID int64 `json:"id,omitempty"`

	/* models
	 */
	Models []string `json:"models,omitempty"`

	/* Name of ModelSet
	 */
	Name string `json:"name,omitempty"`

	/* Link to get this item

	Read Only: true
	*/
	URL strfmt.URI `json:"url,omitempty"`
}

// Validate validates this model set
func (m *ModelSet) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateModels(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelSet) validateModels(formats strfmt.Registry) error {

	if swag.IsZero(m.Models) { // not required
		return nil
	}

	return nil
}
