package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Permission permission

swagger:model Permission
*/
type Permission struct {

	/* Description

	Read Only: true
	*/
	Description string `json:"description,omitempty"`

	/* Dependency parent symbol

	Read Only: true
	*/
	Parent string `json:"parent,omitempty"`

	/* Permission symbol

	Read Only: true
	*/
	Permission string `json:"permission,omitempty"`
}

// Validate validates this permission
func (m *Permission) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
