package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*PermissionSet permission set

swagger:model PermissionSet
*/
type PermissionSet struct {

	/* all access

	Read Only: true
	*/
	AllAccess *bool `json:"all_access,omitempty"`

	/* built in

	Read Only: true
	*/
	BuiltIn *bool `json:"built_in,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID int64 `json:"id,omitempty"`

	/* Name of PermissionSet
	 */
	Name string `json:"name,omitempty"`

	/* permissions
	 */
	Permissions []string `json:"permissions,omitempty"`

	/* Link to get this item

	Read Only: true
	*/
	URL strfmt.URI `json:"url,omitempty"`
}

// Validate validates this permission set
func (m *PermissionSet) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePermissions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PermissionSet) validatePermissions(formats strfmt.Registry) error {

	if swag.IsZero(m.Permissions) { // not required
		return nil
	}

	return nil
}
