package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*ProjectListItem project list item

swagger:model ProjectListItem
*/
type ProjectListItem struct {

	/* id

	Read Only: true
	*/
	ID string `json:"id,omitempty"`
}

// Validate validates this project list item
func (m *ProjectListItem) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
