package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Role role

swagger:model Role
*/
type Role struct {

	/* Unique Id

	Read Only: true
	*/
	ID int64 `json:"id,omitempty"`

	/* model set
	 */
	ModelSet `json:"model_set,omitempty"`

	/* Name of Role
	 */
	Name string `json:"name,omitempty"`

	/* permission set
	 */
	PermissionSet `json:"permission_set,omitempty"`

	/* Link to get this item

	Read Only: true
	*/
	URL strfmt.URI `json:"url,omitempty"`

	/* Link to get list of users with this role

	Read Only: true
	*/
	UsersURL strfmt.URI `json:"users_url,omitempty"`
}

// Validate validates this role
func (m *Role) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
