package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*RunningQueries running queries

swagger:model RunningQueries
*/
type RunningQueries struct {

	/* Cache Key

	Read Only: true
	*/
	CacheKey string `json:"cache_key,omitempty"`

	/* Date/Time Query was completed

	Read Only: true
	*/
	CompletedAt string `json:"completed_at,omitempty"`

	/* Connection ID

	Read Only: true
	*/
	ConnectionID string `json:"connection_id,omitempty"`

	/* Connection

	Read Only: true
	*/
	ConnectionName string `json:"connection_name,omitempty"`

	/* Date/Time Query was initiated

	Read Only: true
	*/
	CreatedAt string `json:"created_at,omitempty"`

	/* Dialect

	Read Only: true
	*/
	Dialect string `json:"dialect,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID int64 `json:"id,omitempty"`

	/* Additional Information(Error message or verbose status)

	Read Only: true
	*/
	Message string `json:"message,omitempty"`

	/* Node Id

	Read Only: true
	*/
	NodeID string `json:"node_id,omitempty"`

	/* Query Id

	Read Only: true
	*/
	QueryID string `json:"query_id,omitempty"`

	/* ID of a Query Task

	Read Only: true
	*/
	QueryTaskID string `json:"query_task_id,omitempty"`

	/* Slug

	Read Only: true
	*/
	Slug string `json:"slug,omitempty"`

	/* Source (look, dashboard, queryrunner, explore, etc.)

	Read Only: true
	*/
	Source string `json:"source,omitempty"`

	/* Status description

	Read Only: true
	*/
	Status string `json:"status,omitempty"`

	/* User who initiated the query

	Read Only: true
	*/
	User `json:"user,omitempty"`
}

// Validate validates this running queries
func (m *RunningQueries) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
