package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*SamlGroupWrite saml group write

swagger:model SamlGroupWrite
*/
type SamlGroupWrite struct {

	/* Name of group in Saml
	 */
	Name string `json:"name,omitempty"`

	/* Looker Role Ids
	 */
	RoleIds []int64 `json:"role_ids,omitempty"`

	/* Link to saml config

	Read Only: true
	*/
	URL strfmt.URI `json:"url,omitempty"`
}

// Validate validates this saml group write
func (m *SamlGroupWrite) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRoleIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SamlGroupWrite) validateRoleIds(formats strfmt.Registry) error {

	if swag.IsZero(m.RoleIds) { // not required
		return nil
	}

	return nil
}
