package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  strfmt "github.com/go-openapi/strfmt"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/validate"
  
  
)



/*SamlGroupRead saml group read

swagger:model SamlGroupRead
*/
type SamlGroupRead struct {
  
  
  /* Name of group in Saml

Read Only: true
 */
Name string `json:"name,omitempty"`

  
  /* Looker Roles

Read Only: true
 */
Roles [] `json:"roles,omitempty"`

  
  /* Link to saml config

Read Only: true
 */
URL strfmt.URI `json:"url,omitempty"`

  
  
  
}


// Validate validates this saml group read
func (m *SamlGroupRead) Validate(formats strfmt.Registry) error {
  var res []error
  
  

  
  
  
  
  if err := m.validateRoles(formats); err != nil {
    // prop
    res = append(res, err)
  }
  
  
  
  
  
  

  if len(res) > 0 {
    return errors.CompositeValidationError(res...)
  }
  return nil
}







func (m *SamlGroupRead) validateRoles(formats strfmt.Registry) error {
  
  if swag.IsZero(m.Roles) { // not required
    return nil
  }
  
  











  return nil
}











