package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*ScheduledPlanDestination scheduled plan destination

swagger:model ScheduledPlanDestination
*/
type ScheduledPlanDestination struct {

	/* Address for recipient (only email addresses supported for now)
	 */
	Address string `json:"address,omitempty"`

	/* Are values formatted? (containing currency symbols, digit separators, etc.
	 */
	ApplyFormatting bool `json:"apply_formatting,omitempty"`

	/* Format requested by the given destination (i.e. PDF, etc.)
	 */
	Format string `json:"format,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID int64 `json:"id,omitempty"`

	/* Id of a scheduled plan you own
	 */
	ScheduledPlanID int64 `json:"scheduled_plan_id,omitempty"`

	/* Type of the address (only 'email' is supported for now)
	 */
	Type string `json:"type,omitempty"`
}

// Validate validates this scheduled plan destination
func (m *ScheduledPlanDestination) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
