package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*StoryListItem story list item

swagger:model StoryListItem
*/
type StoryListItem struct {

	/* file id

	Read Only: true
	*/
	FileID string `json:"file_id,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID string `json:"id,omitempty"`

	/* project

	Read Only: true
	*/
	Project `json:"project,omitempty"`

	/* title

	Read Only: true
	*/
	Title string `json:"title,omitempty"`
}

// Validate validates this story list item
func (m *StoryListItem) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
