package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*StoryAssets story assets

swagger:model StoryAssets
*/
type StoryAssets struct {

	/* css

	Read Only: true
	*/
	CSS string `json:"css,omitempty"`

	/* js

	Read Only: true
	*/
	Js string `json:"js,omitempty"`
}

// Validate validates this story assets
func (m *StoryAssets) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
