package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Timezone timezone

swagger:model Timezone
*/
type Timezone struct {

	/* Timezone group (e.g Common, Other, etc.)

	Read Only: true
	*/
	Group string `json:"group,omitempty"`

	/* Description of timezone

	Read Only: true
	*/
	Label string `json:"label,omitempty"`

	/* Timezone

	Read Only: true
	*/
	Value string `json:"value,omitempty"`
}

// Validate validates this timezone
func (m *Timezone) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
