package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*UserPublic user public

swagger:model UserPublic
*/
type UserPublic struct {

	/* URL for the avatar image (may be generic)

	Read Only: true
	*/
	AvatarURL strfmt.URI `json:"avatar_url,omitempty"`

	/* First Name

	Read Only: true
	*/
	FirstName string `json:"first_name,omitempty"`

	/* Unique Id

	Read Only: true
	*/
	ID int64 `json:"id,omitempty"`

	/* Last Name

	Read Only: true
	*/
	LastName string `json:"last_name,omitempty"`

	/* Link to get this item

	Read Only: true
	*/
	URL strfmt.URI `json:"url,omitempty"`
}

// Validate validates this user public
func (m *UserPublic) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
