package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*UserIDOnly user Id only

swagger:model UserIdOnly
*/
type UserIDOnly struct {

	/* Unique Id

	Read Only: true
	*/
	ID int64 `json:"id,omitempty"`
}

// Validate validates this user Id only
func (m *UserIDOnly) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
