package connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAllConnectionsParams creates a new AllConnectionsParams object
// with the default values initialized.
func NewAllConnectionsParams() *AllConnectionsParams {
	var ()
	return &AllConnectionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAllConnectionsParamsWithTimeout creates a new AllConnectionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAllConnectionsParamsWithTimeout(timeout time.Duration) *AllConnectionsParams {
	var ()
	return &AllConnectionsParams{

		timeout: timeout,
	}
}

/*AllConnectionsParams contains all the parameters to send to the API endpoint
for the all connections operation typically these are written to a http.Request
*/
type AllConnectionsParams struct {

	/*Fields
	  Requested fields.

	*/
	Fields *string

	timeout time.Duration
}

// WithFields adds the fields to the all connections params
func (o *AllConnectionsParams) WithFields(Fields *string) *AllConnectionsParams {
	o.Fields = Fields
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *AllConnectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
